### ISSUE TITLE
Would you mind tell me how to use this repo?

### ISSUE THREAD

**Issue by WwYyFan** [renilJoseph/WriteUsingUR5#1]
@renilJoseph 
     Hi,I'm new to ROS,and I don't know how to use this repo.Would you mind tell me how to use it?

**Comment by WwYyFan** [comment]
when I run 
```
python simple.py A
```
terminal output
```
('Other: ', 0.9999576284983039)
('Other: ', 0.9999576284983039)
('Other: ', 0.9999576284983039)
('Other: ', 0.9999576284983039)
('Other: ', 0.9999576284983036)
('Other: ', 0.9999576284983036)
('Other: ', 0.999957473570906)
('Other: ', 0.999957473570906)
('Other: ', 0.9999576284983036)
('Other: ', 0.9999576284983036)
('Other: ', 0.9999567855582452)
('Other: ', 0.9999567855582452)
Traceback (most recent call last):
  File "simple.py", line 27, in <module>
    getattr(alphabets, 'draw%c' % ch)(rob,a,v)
  File "/home/efun/ur_demo/src/ur_controller/src/alphabets.py", line 43, in drawA
    drawLine(0, 0, -0.4, rob, a, v, True, finalPos)
  File "/home/efun/ur_demo/src/ur_controller/src/alphabets.py", line 27, in drawLine
    return pose #return current position after changing in degree
NameError: global name 'pose' is not defined
```
how to fix it?

**Comment by renilJoseph** [comment]
you could try commenting line 'return pose' in both nextChar and drawLine functions in alphabets.py or try the latest committed code.

It should make it work, otherwise please reply. Sorry, since i could not test it correctly right now.

**Comment by WwYyFan** [comment]
@renilJoseph Thanks for reply.I have tried the new code.There is still an error.
```
Traceback (most recent call last):
  File "draw.py", line 26, in <module>
    getattr(alphabets, 'draw%c' % ch)(rob,a,v)
  File "/home/efun/ur_demo/src/ur_controller/src/alphabets.py", line 48, in drawA
    nextChar(initialPosInMM, a, v)
NameError: global name 'initialPosInMM' is not defined
```

**Comment by renilJoseph** [comment]
it was a spelling mistake. i think i cleared it.

**Comment by renilJoseph** [comment]
@WwYyFan sorry for testing it out late. You can give command "python simple.py BC" and it will write 'BC'. Please checkout the orientation.gif file, which specify the direction in which board should be placed.
